#!/usr/bin/env bash
# A bash script to install Nginx server
apt-get update
apt-get -y install nginx
echo "Hello World!" > sudo tee /var/www/html/index.html
sudo service nginx restart
sudo service nginx enable
exit 0
