#!/usr/bin/env bash
# A script to Install and configure HAproxy on your lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy
config=\
'
backend bolanle-backend
	balance roundrobin
	server 192925-web-01 35.168.2.24 check
	server 192925-web-02 100.26.222.48 check
frontend bolanle-frontend
	bind *:80
        mode http
        default_backend bolanle-backend
'
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
